[project]
name = "weather"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.12.3",
    "neo4j>=5.0.0",
    "pymilvus>=2.4.0",
    "psycopg[binary]>=3.1.8",
]
